name: Update Pubs

on:
  schedule:
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  updateBib:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:  
      - name: Download Bib from DBLB
        run: wget -c https://dblp.uni-trier.de/pid/294/4314.bib -O lib.bib
        
      - name: Convert Bib to CSL JSON
        uses: docker://pandoc/core:2.18
        with:
          args: "-r bibtex lib.bib -w csljson -o lib.json"
      
      - name: Update repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update bib
          commit_user_name: cric96 # defaults to "github-actions[bot]"
          commit_user_email: gianluca.aguzzi@unibo.it # defaults to "github-actions[bot]@users.noreply.github.com"
          commit_author: cric96 <gianluca.aguzzi@unibo.it> # defaults to author of the commit that triggered the run

